steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/korsify-app/korsify:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/korsify-app/korsify:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'korsify'
      - '--image'
      - 'gcr.io/korsify-app/korsify:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances'
      - 'korsify-app:us-central1:korsify-db'
      - '--set-env-vars'
      - 'NODE_ENV=production,PORT=8080'
      - '--set-secrets'
      - 'GEMINI_API_KEY=GEMINI_API_KEY:latest,JWT_SECRET=JWT_SECRET:latest,DATABASE_URL=DATABASE_URL:latest'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'

# Store images in Container Registry
images:
  - 'gcr.io/korsify-app/korsify:$COMMIT_SHA'
  - 'gcr.io/korsify-app/korsify:latest'

# Build timeout
timeout: '1200s'